services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:Kris11063@db/pharmacy_db
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Kris11063
      - POSTGRES_DB=pharmacy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: